import { test, expect } from '@playwright/test';
test('桌面课表：复合筛选、重叠展开与真实周次', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto('/');
  await expect(page.getByText('开发演示 · 以下课程和登记均为合成数据')).toBeVisible();
  await expect(page.getByRole('button', { name: '机器学习 · 演示，不考勤' })).toBeVisible();
  await page.getByRole('button', { name: /4 门课程/ }).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await expect(page.getByRole('dialog').getByRole('button')).toHaveCount(5);
  await page.getByRole('button', { name: '关闭', exact: true }).click();
  await page.getByRole('button', { name: /^不考勤/ }).click();
  await expect(page.locator('.course-card')).toHaveCount(3);
  await page.getByLabel('搜索课程').fill('机器学习');
  await expect(page.locator('.course-card')).toHaveCount(1);
  await page.getByLabel('教学周').selectOption('20');
  await expect(page.getByText('没有符合条件的课程')).toBeVisible();
  await page.getByLabel('教学周').selectOption('1');
  await page.getByRole('button', { name: '重置' }).click();
  await page.screenshot({ path: 'output/playwright/desktop.png', fullPage: true });
});
test('学生登录、导入幂等、反馈提交、管理员审核更新颜色', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('button', { name: '登录 / 导入课表' }).click();
  await page.getByRole('button', { name: '演示同学登录', exact: true }).click();
  await expect(page.getByLabel('同班显示昵称')).toHaveValue('演示同学');
  await page.getByRole('button', { name: '预览合成课程导入' }).click();
  await expect(page.getByRole('heading', { name: '确认导入课程' })).toBeVisible();
  await page.getByRole('button', { name: '确认导入', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.getByLabel('只看我的课程').check();
  await page.getByRole('button', { name: '机器学习 · 演示，不考勤' }).click();
  await expect(page.getByText('同班同学', { exact: true })).toBeVisible();
  await expect(page.locator('.classmates')).toContainText('演示管理员');
  await page.getByLabel('你了解的考勤情况').selectOption('red');
  await page.getByLabel('简要说明').fill('测试反馈：连续两次点名');
  await page.getByRole('button', { name: '提交反馈' }).click();
  await expect(page.getByRole('status')).toContainText('反馈已提交');
  await page.getByRole('button', { name: '关闭', exact: true }).click();
  await expect(page.getByRole('button', { name: '机器学习 · 演示，不考勤' })).toBeVisible();
  await page.getByRole('button', { name: '演示同学', exact: true }).click();
  await page.getByRole('button', { name: '演示管理员登录', exact: true }).click();
  await page.getByRole('button', { name: '关闭', exact: true }).click();
  await page.getByRole('button', { name: '审核管理', exact: true }).click();
  await page.getByLabel('处理说明 机器学习 · 演示').fill('已核实，采纳反馈');
  await page.getByRole('button', { name: '采纳并更新颜色' }).click();
  await expect(page.getByText('暂无待审核反馈')).toBeVisible();
  await page.getByRole('button', { name: '关闭', exact: true }).click();
  await expect(page.getByRole('button', { name: '机器学习 · 演示，严格考勤' })).toBeVisible();
});
test('手机按日展示且页面没有横向溢出', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/');
  await expect(page.locator('.day-list')).toBeVisible();
  await page.getByRole('button', { name: '周三', exact: true }).click();
  await expect(page.locator('.day-list')).toContainText('计算机网络');
  await page.getByRole('button', { name: '筛选', exact: true }).click();
  await expect(page.getByLabel('搜索课程')).toBeVisible();
  await page.getByLabel('搜索课程').fill('计算机网络');
  await page.getByRole('button', { name: '筛选', exact: true }).click();
  await expect(page.locator('.day-list .list-course')).toHaveCount(1);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'output/playwright/mobile.png', fullPage: true });
});
